hanoi(3,
      left,
      right,
      center,
      [[left, right],
       [left, center],
       [right, center],
       [left, right],
       [center, left],
       [center, right],
       [left, right]]).

clause(1, append([], var('Ys'), var('Ys')), true).
clause(2,
       append([var('X')|var('Xs')], var('Ys'), [var('X')|var('Zs')]),
       append(var('Xs'), var('Ys'), var('Zs'))).
clause(3, hanoi(0, anonymous(1), anonymous(2), anonymous(3), []), true).
clause(4,
       hanoi(var('N'), var('From'), var('To'), var('Via'), var('Moves')),
       (var('N') > 0,
        var('Smaller') is var('N') - 1,
        hanoi(var('Smaller'), var('From'), var('Via'), var('To'), var('Before')),
        hanoi(var('Smaller'), var('Via'), var('To'), var('From'), var('After')),
        append(var('Before'), [[var('From'), var('To')]|var('After')], var('Moves')))).

step(hanoi(3, left, right, center, [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]),
     rule(4),
     ['N' = 3,
      'From' = left,
      'To' = right,
      'Via' = center,
      'Moves' = [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]],
      'Smaller' = 2,
      'Before' = [[left, right], [left, center], [right, center]],
      'After' = [[center, left], [center, right], [left, right]]],
     [3 > 0,
      2 is 3 - 1,
      hanoi(2, left, center, right, [[left, right], [left, center], [right, center]]),
      hanoi(2, center, right, left, [[center, left], [center, right], [left, right]]),
      append([[left, right], [left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]])]).
step(3 > 0, builtin, [], []).
step(2 is 3 - 1, builtin, [], []).
step(hanoi(2, left, center, right, [[left, right], [left, center], [right, center]]),
     rule(4),
     ['N' = 2,
      'From' = left,
      'To' = center,
      'Via' = right,
      'Moves' = [[left, right], [left, center], [right, center]],
      'Smaller' = 1,
      'Before' = [[left, right]],
      'After' = [[right, center]]],
     [2 > 0,
      1 is 2 - 1,
      hanoi(1, left, right, center, [[left, right]]),
      hanoi(1, right, center, left, [[right, center]]),
      append([[left, right]], [[left, center], [right, center]], [[left, right], [left, center], [right, center]])]).
step(2 > 0, builtin, [], []).
step(1 is 2 - 1, builtin, [], []).
step(hanoi(1, left, right, center, [[left, right]]),
     rule(4),
     ['N' = 1,
      'From' = left,
      'To' = right,
      'Via' = center,
      'Moves' = [[left, right]],
      'Smaller' = 0,
      'Before' = [],
      'After' = []],
     [1 > 0,
      0 is 1 - 1,
      hanoi(0, left, center, right, []),
      hanoi(0, center, right, left, []),
      append([], [[left, right]], [[left, right]])]).
step(1 > 0, builtin, [], []).
step(0 is 1 - 1, builtin, [], []).
step(hanoi(0, left, center, right, []), fact(3), [], []).
step(hanoi(0, center, right, left, []), fact(3), [], []).
step(append([], [[left, right]], [[left, right]]), fact(1), ['Ys' = [[left, right]]], []).
step(hanoi(1, right, center, left, [[right, center]]),
     rule(4),
     ['N' = 1,
      'From' = right,
      'To' = center,
      'Via' = left,
      'Moves' = [[right, center]],
      'Smaller' = 0,
      'Before' = [],
      'After' = []],
     [1 > 0,
      0 is 1 - 1,
      hanoi(0, right, left, center, []),
      hanoi(0, left, center, right, []),
      append([], [[right, center]], [[right, center]])]).
step(hanoi(0, right, left, center, []), fact(3), [], []).
step(append([], [[right, center]], [[right, center]]), fact(1), ['Ys' = [[right, center]]], []).
step(append([[left, right]], [[left, center], [right, center]], [[left, right], [left, center], [right, center]]),
     rule(2),
     ['X' = [left, right],
      'Xs' = [],
      'Ys' = [[left, center], [right, center]],
      'Zs' = [[left, center], [right, center]]],
     [append([], [[left, center], [right, center]], [[left, center], [right, center]])]).
step(append([], [[left, center], [right, center]], [[left, center], [right, center]]),
     fact(1),
     ['Ys' = [[left, center], [right, center]]],
     []).
step(hanoi(2, center, right, left, [[center, left], [center, right], [left, right]]),
     rule(4),
     ['N' = 2,
      'From' = center,
      'To' = right,
      'Via' = left,
      'Moves' = [[center, left], [center, right], [left, right]],
      'Smaller' = 1,
      'Before' = [[center, left]],
      'After' = [[left, right]]],
     [2 > 0,
      1 is 2 - 1,
      hanoi(1, center, left, right, [[center, left]]),
      hanoi(1, left, right, center, [[left, right]]),
      append([[center, left]], [[center, right], [left, right]], [[center, left], [center, right], [left, right]])]).
step(hanoi(1, center, left, right, [[center, left]]),
     rule(4),
     ['N' = 1,
      'From' = center,
      'To' = left,
      'Via' = right,
      'Moves' = [[center, left]],
      'Smaller' = 0,
      'Before' = [],
      'After' = []],
     [1 > 0,
      0 is 1 - 1,
      hanoi(0, center, right, left, []),
      hanoi(0, right, left, center, []),
      append([], [[center, left]], [[center, left]])]).
step(append([], [[center, left]], [[center, left]]), fact(1), ['Ys' = [[center, left]]], []).
step(append([[center, left]], [[center, right], [left, right]], [[center, left], [center, right], [left, right]]),
     rule(2),
     ['X' = [center, left],
      'Xs' = [],
      'Ys' = [[center, right], [left, right]],
      'Zs' = [[center, right], [left, right]]],
     [append([], [[center, right], [left, right]], [[center, right], [left, right]])]).
step(append([], [[center, right], [left, right]], [[center, right], [left, right]]),
     fact(1),
     ['Ys' = [[center, right], [left, right]]],
     []).
step(append([[left, right], [left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]),
     rule(2),
     ['X' = [left, right],
      'Xs' = [[left, center], [right, center]],
      'Ys' = [[left, right], [center, left], [center, right], [left, right]],
      'Zs' = [[left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]],
     [append([[left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, center], [right, center], [left, right], [center, left], [center, right], [left, right]])]).
step(append([[left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]),
     rule(2),
     ['X' = [left, center],
      'Xs' = [[right, center]],
      'Ys' = [[left, right], [center, left], [center, right], [left, right]],
      'Zs' = [[right, center], [left, right], [center, left], [center, right], [left, right]]],
     [append([[right, center]], [[left, right], [center, left], [center, right], [left, right]], [[right, center], [left, right], [center, left], [center, right], [left, right]])]).
step(append([[right, center]], [[left, right], [center, left], [center, right], [left, right]], [[right, center], [left, right], [center, left], [center, right], [left, right]]),
     rule(2),
     ['X' = [right, center],
      'Xs' = [],
      'Ys' = [[left, right], [center, left], [center, right], [left, right]],
      'Zs' = [[left, right], [center, left], [center, right], [left, right]]],
     [append([], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [center, left], [center, right], [left, right]])]).
step(append([], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [center, left], [center, right], [left, right]]),
     fact(1),
     ['Ys' = [[left, right], [center, left], [center, right], [left, right]]],
     []).
